const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const model=require('../psa-plan-model'),{run}=require('./run_daily_sources');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'daily-isolation-'));fs.mkdirSync(path.join(root,'data'));
const called=[];
const result=run([{source:'psaJapan'},{source:'shopBuyback'},{source:'hareruya2'}],t=>{called.push(t.source);return {status:t.source==='psaJapan'?1:0,stderr:'HTTP 403'};},root);
assert.deepEqual(called,['psaJapan','shopBuyback','hareruya2']);assert.equal(result.status,'partial-with-failure');
const valid={price:11980,businessDays:80,calendarDays:112,declaredValueMax:250000};
assert.equal(model.problem(valid),null);assert(model.problem({...valid,price:null}));assert(model.problem({...valid,calendarDays:7}));assert(model.problem({...valid,validationStatus:'held'}));
const blocks=model.definitions.map(([id,name])=>`${name} ￥11,980/枚 予定納期：80営業日（日数換算：約112日）申告価格：￥250,000以下`).join(' ');
assert(model.parse('スタンダードとは説明です '+blocks).every(p=>p.plan));
assert(model.parse(blocks.replace('￥11,980','金額なし')).find(p=>p.id==='standard').plan===null);
assert(model.parse(blocks+' スタンダード ￥9,980/枚 予定納期：100営業日（日数換算：約140日）申告価格：￥150,000以下').find(p=>p.id==='standard').plan===null);
const workflow=fs.readFileSync(path.join(__dirname,'../.github/workflows/daily-fast-update.yml'),'utf8');
assert(!workflow.includes('continue-on-error'));assert(workflow.indexOf('Run fast regression tests')<workflow.indexOf('Commit changed data only'));
assert(workflow.indexOf('Commit changed data only')<workflow.indexOf('Report independent acquisition failures'));
assert(!fs.readFileSync(path.join(__dirname,'update_psa_japan_services.js'),'utf8').includes('r.jina.ai'));
const builder=fs.readFileSync(path.join(__dirname,'build_purchase_limit_audit.js'),'utf8');
const prefix=builder.slice(0,builder.indexOf('const calculated = prepareCalculatedCards(state.cards);'));
new Function('require','__dirname','process','assert',prefix+`
vm.runInContext('globalThis.planApi={psaPlanProblem,calculatedCardsForSearch};',context);
state.cards=state.cards.slice(0,1);
assert.equal(context.planApi.psaPlanProblem(),null);
const good=context.planApi.calculatedCardsForSearch(state.cards);
state.psaServices={...state.psaServices,plans:state.psaServices.plans.map(p=>({...p,validationStatus:'held'}))};
const held=context.planApi.calculatedCardsForSearch(state.cards);
assert.notStrictEqual(good,held);
assert.equal(held[0].purchaseDecision.verdict,'要確認');
assert.equal(held[0].purchaseAvailability.verifiedNow,false);
state.psaServices=null;
assert(context.planApi.psaPlanProblem());
assert.equal(currentMarketView(held[0]).cap,null);
`)(require,__dirname,process,assert);
console.log('daily source isolation and plan safety tests passed');
