const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path');
const horizon = require('../return-horizon-model.js'), reference = require('../price-reference-model.js');
const release = require('./catalog_semantics.js'), years = require('../release-year-filter.js');
const memo = require('../purchase-memo-model.js'), decision = require('../decision-model.js');
const {observe} = require('./fixed_freshness.js');
const {exactIdentity} = require('./refresh_candidate_shops.js');
const dates = Array.from({length:151},(_,i)=>new Date(Date.UTC(2026,0,1)+i*86400000).toISOString().slice(0,10));
const history={dates,cards:Object.fromEntries(Array.from({length:35},(_,i)=>[`c${i}`,dates.map((d,j)=>[d,20000-j,50000-j*100,0,0,0,10,30])]))};
const calibration=horizon.calibrate(history,dates.at(-1));
for(const days of horizon.DAYS){
  const row=horizon.resolve({currentPrice:50000,days,calibration});
  assert.equal(row.available,true); assert.equal(row.approved,false);
  assert.equal(row.horizonDays,days); assert(row.bearishPrice<=row.centralPrice);
  const trial=memo.trial({purchasePrice:15000,fee:13000,currentPrice:50000,lockDays:days,forecastHorizonDays:days,forecastReferenceOnly:true,
    limit:{assumptions:{hitRate:.7,lowerGradePrice:20000},modelInput:{forecastPrice:row.centralPrice,saleFeeRate:8,saleExtraCost:1000},stressForecastPrice:row.bearishPrice}},decision);
  assert.equal(trial.periodMatched,true);assert.match(trial.warning,/参考試算/);
  assert(Number.isFinite(trial.rows.central.expectedProfit));
}
const oneStart=horizon.calibrate({...history,dates:[dates[0],dates[42]],cards:Object.fromEntries(Object.entries(history.cards).map(([id,r])=>[id,[r[0],r[42]]]))},dates[42]);
assert.equal(oneStart.horizons[42].all.originDates,1);
assert.equal(horizon.resolve({currentPrice:50000,days:42,calibration:oneStart}).approved,false);
assert.equal(horizon.resolve({currentPrice:50000,days:91,calibration:oneStart}).centralPrice,null);
assert.equal(horizon.calibrate(history,dates[41]).horizons[42].all.pairs,0,'no future leakage');
assert.equal(horizon.resolve({currentPrice:null,days:42,calibration}).available,false);
assert(horizon.resolve({currentPrice:100,days:42,calibration:{horizons:{42:{under30k:calibration.horizons[42].all}}}}).centralPrice>0);
const h={dates:[dates[0],dates[30]],cards:{a:[[dates[0],100,100,0,0,0,5,30],[dates[30],80,70,0,0,0,5,30]]}};
const first=reference.build(h,{}, {a:{supportBroken:true,supportConfirmed:true,supportLow:90,supportHigh:95}},dates[30]);
assert.equal(first.cards.a.raw30,-19.999999999999996);
assert.equal(first.cards.a.psa10Index,70);
assert.equal(first.cards.a.psa1090,null);
const expanded=reference.build({...h,cards:{...h.cards,b:[[dates[30],500,500]]}},first,{a:{supportLow:60,supportHigh:65,supportBroken:false}},dates[30]);
assert.deepEqual(expanded.cohort,['a']);assert.equal(expanded.indices.at(-1).psa10Index,70);
assert.equal(expanded.cards.a.breakdownUnresolved,true,'moving support lower cannot erase the break');
assert.equal(expanded.cards.a.supportEvents[0].detectedAt,dates[30]);
const missing=reference.build({...h,cards:{a:[h.cards.a[0]]}},first,{},dates[30]);
assert.equal(missing.indices.at(-1).psa10Index,null,'missing cohort member is not a changed market');
const rolled=reference.build({dates:[dates[30]],cards:{a:[h.cards.a[1]]}},first,{},dates[30]);
assert.equal(rolled.cards.a.psa10Index,70,'baseline survives retention rollover');
const vanished=reference.build({dates:[dates[30]],cards:{}},first,{},dates[30]);
assert.equal(vanished.cards.a.breakdownUnresolved,true,'support warning survives a missing or archived card');
const resolved={...first,cards:{...first.cards,a:{...first.cards.a,supportEvents:first.cards.a.supportEvents.map(e=>({...e,resolvedAt:dates[30]}))}}};
const brokenAgain=reference.build(h,resolved,{a:{supportBroken:true,supportConfirmed:true,supportLow:90,supportHigh:95}},dates[30]);
assert.equal(brokenAgain.cards.a.supportEvents.length,2,'new break of previously recovered band is retained');
const noncohort=reference.build({dates:[dates[0],dates[30]],cards:{a:h.cards.a,b:[[dates[0],300,400],[dates[30],null,200]]}}, {}, {},dates[30]);
assert(!noncohort.cohort.includes('b'));
const retained=reference.build({dates:[dates[30]],cards:{a:[h.cards.a[1]],b:[[dates[30],150,200]]}},noncohort,{},dates[30]);
assert.equal(retained.cards.b.rawIndex,50,'individual fixed baseline survives even outside market cohort');
assert.equal(reference.windowReturn([[dates[0],100,100],[dates[0],200,200],[dates[30],100,100]],dates[30],30,2),-50,'one latest record per day');
const cost={purchasePrice:30000,gradingFee:13000,extraCost:1000,feeRate:8,hitRate:.7,lowerGradePrice:20000};
assert.equal(reference.fixedBreakEven(cost),reference.fixedBreakEven({...cost,currentMarketPrice:1}));
assert.equal(reference.fixedBreakEven({...cost,hitRate:null}),null);
assert.equal(reference.fixedBreakEven({...cost,feeRate:100}),null);
assert.equal(reference.fixedBreakEven({...cost,psa10Multiplier:0}),null);
const shopAnchor=reference.fixedBreakEven({...cost,psa10Multiplier:.8});
assert(Math.abs(.7*shopAnchor*.8+.3*20000*.92-1000-30000-13000)<1e-6,'buyback rate and deduction included without duplicate marketplace fee');
assert.equal(release.resolveRelease({setCode:'SV99',name:'not officially registered'}).year,null,'do not guess release year');
assert.equal(release.resolveRelease({setCode:'WCS23',name:'example'}).date,'2023-07-28');
assert.equal(release.resolveRelease({setCode:'S-P',model:'323',name:'ピカチュウ: プロモ[323 S-P]'}).year,2022);
assert.equal(release.resolveRelease({setCode:'S-P',model:'323',name:'different promo[323 S-P]'}).year,null);
assert.equal(years.matches({releaseYear:2019},{},true,false),false);
assert.equal(years.matches({releaseYear:2020},{},true,false),true);
assert.equal(years.matches({siteAddedAt:'2026-01-01'},{},true,false),false);
const card={name:'ゼクロムGX SR: 争奪戦プロモ[SM-P 239]',model:'239'};
assert.equal(exactIdentity(card,{title:'ゼクロムGX(PROMO){雷}〈239/SM-P〉[SM-P]'}),true);
assert.equal(exactIdentity(card,{title:'ゼクロムGX(PROMO){雷}〈238/SM-P〉[SM-P]'}),false);
assert.equal(exactIdentity(card,{title:'【未開封プロモ】 ゼクロムGX(PROMO){雷}〈239/SM-P〉[SM-P]'}),false);
const now=Date.parse('2026-10-03T22:00:00Z'),monitor={sources:{shop:{cards:[{id:'a',lastConfirmedAt:new Date(now-3*3600000).toISOString(),status:'期限内'},{id:'b',lastConfirmedAt:null,status:'手動確認待ち'}]}}};
const observations=observe({},monitor,now);
const later=observe(observations,{sources:{shop:{cards:[...monitor.sources.shop.cards,{id:'c',lastConfirmedAt:new Date(now).toISOString(),status:'期限内'}]}}},now+3600000);
assert.equal(later.sources.shop.observations.at(-1).cohort,2);assert.equal(later.sources.shop.observations.at(-1).fresh6hPct,50);
assert.equal(later.sources.shop.observations.at(-1).added,1);assert.equal(later.sources.shop.observations.length,2);
const root=path.join(__dirname,'..'),app=fs.readFileSync(path.join(root,'app.js'),'utf8');
assert.match(app,/finally \{state.fee=oldFee;state.lockDays=oldDays;/);
assert.match(app,/referenceChunks.has\(file\)/);assert.match(app,/購入時固定損益分岐JSON/);
assert.match(app,/返却\$\{state.lockDays\}日・期待利益（参考）/);
const pokeWorkflow=fs.readFileSync(path.join(root,'.github/workflows/backfill-data.yml'),'utf8');
assert(!/update_torecacamp|run_safe_backfill/.test(pokeWorkflow),'PokeDATA does not duplicate Camp crawling');
assert.match(fs.readFileSync(path.join(root,'.github/workflows/daily-fast-update.yml'),'utf8'),/fixed-price-reference.json/);
assert(!JSON.stringify(observations).includes('NaN'));assert(!JSON.stringify(first).includes('Infinity'));
console.log('return periods, no extrapolation, fixed cohort, persistent support break, immutable purchase basis, official release, checkpoint, missing-value and lazy-load tests passed');
