const assert=require('node:assert/strict'),postpass=require('./camp_postpass');
const now=Date.parse('2026-10-10T00:00:00Z');
const p={totalSitemaps:46,processedSitemaps:Array.from({length:46},(_,i)=>i+1),currentSitemapIndex:46,currentEntryIndex:0};
assert(postpass.prepare(p,46,now));assert.equal(p.currentSitemapIndex,45);assert(p.firstPassCompletedAt);
p.currentEntryIndex=22;postpass.checkpoint(p,46);postpass.prepare(p,46,now);assert.equal(p.currentEntryIndex,22);
p.currentSitemapIndex=46;postpass.checkpoint(p,46);assert.equal(p.maintenance.sitemapIndex,0);assert.equal(p.maintenance.cycles,1);
postpass.checkpoint(p,46);assert.equal(p.maintenance.cycles,1);
assert(postpass.due({observedAt:new Date(now-7*3600000).toISOString()},true,now));
assert(!postpass.due({observedAt:new Date(now-7*3600000).toISOString()},false,now));
assert(!postpass.due({observedAt:new Date(now+1).toISOString()},true,now));
assert(!postpass.prepare({...p,retryByUrl:{bad:{}}},46,now));
const batch=require('./source_batch_metrics').shopBatch('torecacamp',JSON.stringify({torecacamp:{detailFetched:4,coverage:6502,updated:1,linked:0}}));
assert.equal(batch.acquiredCount,4);assert.equal(batch.catalogCount,6502);assert.equal(batch.newLinkedCount,0);
console.log('postpass continuation tests passed');
const observe=require('./effective_price_cadence').observe;
const proof={pipelines:{priority:{confirmed:true,runId:1}}},receipts={pipelines:{priority:{runId:1,recordedAt:new Date(now-3*3600000).toISOString(),cardObservations:{hareruya2:[{id:'a',at:new Date(now-3*3600000).toISOString()}]}}}};
const first=observe({},proof,receipts,now);assert.equal(first.sources.hareruya2.maximumIntervalMs,null);
const second=observe(first,{pipelines:{catchup:{confirmed:true,runId:2}}},{pipelines:{catchup:{runId:2,recordedAt:new Date(now).toISOString(),cardObservations:{hareruya2:[{id:'a',at:new Date(now).toISOString()}]}}}},now);
assert.equal(second.sources.hareruya2.maximumIntervalMs,3*3600000);assert.equal(second.sources.hareruya2.byRoute.catchup,1);
assert.equal(observe(second,{pipelines:{catchup:{confirmed:false,runId:3}}},{pipelines:{catchup:{runId:3}}},now).runs.length,2);
