const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const ratio = require('../purchase-ratio-model.js');
const model = require('../decision-model.js');
const {observe} = require('./fixed_freshness.js');
const {confirmedInventoryAt} = require('./priority_price_queue.js');
const input = {purchasePrice:30000,fee:13000,forecastPrice:100000,saleFeeRate:8,saleExtraCost:1000,lockDays:91,
  assumptions:{hitRate:.7,lowerGradePrice:40000},minExpectedProfit:10000,minExpectedRoi:30,minAnnualEfficiency:40,
  qualityScore:80,capital:500000,lockedCapital:0,gradingReserve:130000,submissionCount:10,maxCapitalShare:100};
const focused = ratio.roiOnly(input);
const decide = args => model.purchaseDecision({...args,economics:model.expectedEconomics(args),capital:model.capitalPlan({...args,psaCapital:500000}),economicMaxPrice:40000});
assert.equal(focused.minExpectedProfit,0);
assert.equal(focused.minExpectedRoi,30);assert.equal(focused.minAnnualEfficiency,40);
const economics = model.expectedEconomics(focused);
assert(economics.expectedProfit > 0);
assert.equal(economics.expectedProfit,model.expectedEconomics(input).expectedProfit);
assert.equal(economics.expectedRoi,economics.expectedProfit/(30000+13000)*100);
assert.equal(model.expectedEconomics({...focused,fee:14000}).expectedProfit,economics.expectedProfit-1000);
assert.equal(model.expectedEconomics({...focused,saleExtraCost:2000}).expectedProfit,economics.expectedProfit-1000);
assert(model.expectedEconomics({...focused,saleFeeRate:10}).expectedProfit<economics.expectedProfit);
assert(model.expectedEconomics({...focused,purchasePrice:100000}).expectedProfit<0);
assert(decide({...focused,purchasePrice:100000}).verdict !== 'GO');
const boundary = {...focused,minExpectedRoi:economics.expectedRoi,minAnnualEfficiency:0,economicMaxPrice:40000};
assert(!decide(boundary).reasons.some(r=>r.includes('最低期待利益率')));
assert(decide({...boundary,minExpectedRoi:economics.expectedRoi+.001}).reasons.some(r=>r.includes('最低期待利益率')));
const base = {purchasePrice:40000,purchaseKind:'store',psa9:{value:50000,measurementType:'actual',count:3,updatedAt:'2026-10-05',country:'jp',currency:'JPY',identityConfirmed:true},
  asOf:'2026-10-06',fee:13000,saleFeeRate:8,extraCost:1000};
const exact = ratio.evaluate(base);
assert.equal(exact.ratio,80);assert.equal(exact.nonLossCap,32000);
assert(ratio.matches(exact,null,80));assert(ratio.matches(exact,80,100));assert(!ratio.matches(exact,100,null));
const aggregate = ratio.evaluate({...base,psa9:{...base.psa9,measurementType:'aggregate'}});
assert.equal(ratio.matches(aggregate,0,100),false);assert(ratio.matches(aggregate,0,100,true));
assert.equal(ratio.evaluate({...base,psa9:{value:null}}).ratio,null);
assert.equal(ratio.evaluate({...base,psa9:{...base.psa9,value:0}}).ratio,null);
assert.equal(ratio.evaluate({...base,purchasePrice:null}).ratio,null);
assert.equal(ratio.evaluate({...base,conflicted:true}).ratio,null);
assert.equal(ratio.evaluate({...base,psa9:{...base.psa9,currency:'USD'}}).ratio,null);
assert.equal(ratio.evaluate({...base,psa9:{...base.psa9,identityConfirmed:false}}).ratio,null);
assert.equal(ratio.evaluate({...base,psa9:{...base.psa9,updatedAt:'2026-08-01'}}).ratio,null);
assert.equal(ratio.evaluate({...base,psa9:{...base.psa9,count:1}}).ratio,null);
assert(ratio.evaluate({...base,purchaseKind:'market'}).reference);
assert.equal(ratio.evaluate({...base,fee:-1}).nonLossCap,null);
assert.equal(ratio.evaluate({...base,purchasePrice:Infinity}).ratio,null);
const inventory={updatedAt:'2026-10-05',total:2,cards:[{id:'a'},{id:'b'}]};
const success={status:'success',lastSuccessAt:'2026-10-05T16:50:19Z',acquiredCount:2};
assert.equal(confirmedInventoryAt(inventory,success),success.lastSuccessAt,'unchanged inventory can be revalidated after JST midnight');
assert.equal(confirmedInventoryAt(inventory,{...success,status:'failed'}),null);
assert.equal(confirmedInventoryAt(inventory,{...success,acquiredCount:0}),null);
const now=Date.parse(success.lastSuccessAt);
const first=observe({}, {sources:{test:{cards:[{id:'a',lastConfirmedAt:success.lastSuccessAt,status:'期限内'}]}}},now);
const next=observe(first,{sources:{test:{cards:[],fixedCards:[{id:'a',lastConfirmedAt:success.lastSuccessAt,status:'期限内'}]}}},now+1000);
assert.equal(next.sources.test.observations.at(-1).fresh6h,1);
assert.equal(next.sources.test.observations.at(-1).missingFromCurrent,1);
assert.equal(next.sources.test.observations.at(-1).unconfirmed,0);
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const elements = new Map();
const document = {getElementById:id=>{if(!elements.has(id))elements.set(id,{value:'',checked:false});return elements.get(id);},querySelectorAll:()=>[]};
let saved={};
const localStorage={getItem:k=>saved[k]??null,setItem:(k,v)=>{saved[k]=v;}};
const context=vm.createContext({window:{location:{href:'https://example.test/?expProfit=0&expRoi=30&annual=40&psa9RatioMin=80&psa9RatioMax=100&psa9RatioRef=1'},PurchaseRatioModel:ratio,PurchaseDecisionModel:model},document,URL,URLSearchParams,localStorage,console,setTimeout,clearTimeout});
vm.runInContext(source.split('// Browser event bindings start here;')[0]+`\nglobalThis.api={state,els,readUrl,buildShareUrl,restoreQuickFilters,saveQuickFilters,purchasePsa9Ratio,signedExpectedMoney,favoritePurchasePrice};`,context);
const api=context.api;
api.readUrl();assert.equal(api.els.minExpectedProfitInput.value,'0');assert.equal(api.els.psa9RatioMinInput.value,'80');assert(api.els.psa9RatioReferenceInput.checked);
Object.assign(api.state,{minExpectedProfit:0,minExpectedRoi:30,minAnnualEfficiency:40,psa9RatioMin:80,psa9RatioMax:100,psa9RatioReference:true});
const url=api.buildShareUrl();assert.equal(url.searchParams.get('expProfit'),'0');assert.equal(url.searchParams.get('psa9RatioMax'),'100');
api.saveQuickFilters();api.els.minExpectedProfitInput.value='10000';context.window.location.href='https://example.test/';api.restoreQuickFilters();assert.equal(api.els.minExpectedProfitInput.value,'0');
context.window.location.href='https://example.test/?expProfit=1000';api.readUrl();api.restoreQuickFilters();assert.equal(api.els.minExpectedProfitInput.value,'1000');
const favorite = {id:'test',price:40000,currentStoreOffer:{value:30000},psa9Audit:{...base.psa9,measurementType:'aggregate'}};
assert.equal(api.purchasePsa9Ratio(favorite,40000,'market').purchasePrice,40000);
assert.equal(api.purchasePsa9Ratio(favorite,40000,'market').purchaseKind,'market');
assert.equal(api.purchasePsa9Ratio(favorite,null).purchasePrice,30000);
assert.equal(api.signedExpectedMoney(null).text,'算出不可');
assert.equal(api.signedExpectedMoney(0).text,'¥0');
assert.equal(api.signedExpectedMoney(-1000).text,'-¥1,000');
api.state.favoriteCosts.test=null;assert.equal(api.favoritePurchasePrice(favorite),40000);
api.state.favoriteCosts.test=0;assert.equal(api.favoritePurchasePrice(favorite),0);
const tasks = require('./task_operations.js').build(root);
assert(tasks.aiFollowup.status.startsWith('PAUSED'));assert.equal(tasks.aiFollowup.originalRequestComplete,false);
assert(tasks.scripts.every(r=>r.llmCalls===0 && r.codexCalls===0));
assert(tasks.scripts.some(r=>r.name==='Manual Full Refresh' && r.schedule==='自動更新なし・手動のみ'));
console.log('ROI zero/boundaries/costs, PSA9 provenance/null/reference ratios, URL/reload, fixed-cohort and revalidation tests passed');
