const assert = require('node:assert/strict');
const { measuredDeadlineRun } = require('./refresh_capacity');
const now = Date.parse('2026-10-11T00:00:00Z');
const r = {sourceId:'hareruya2',mode:'deadline-price-refresh',startedAt:'2026-10-10T00:00:00Z',refreshedCount:100,durationMs:300000};
assert.equal(measuredDeadlineRun([r,{...r,mode:'completion-backfill',refreshedCount:7,durationMs:13000}],r.sourceId,now).refreshedCount,100);
assert.equal(measuredDeadlineRun([{...r,mode:'completion-backfill'}],r.sourceId,now),null);
assert.equal(measuredDeadlineRun([{...r,startedAt:'2026-10-12T00:00:00Z'}],r.sourceId,now),null);
assert.equal(measuredDeadlineRun([{...r,startedAt:'2026-09-01T00:00:00Z'}],r.sourceId,now),null);
assert.equal(measuredDeadlineRun([r,{...r,refreshedCount:200},{...r,refreshedCount:300}],r.sourceId,now).refreshedCount,200);
console.log('Deadline capacity sample isolation passed');
