const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { plan, finish } = require("./priority_price_queue.js");
const { due } = require("./run_priority_price_refresh.js");
const years = require("../release-year-filter.js");
const model = require("../decision-model.js");
const memo = require("../purchase-memo-model.js");
const now = Date.parse("2026-10-03T14:59:00Z");
const cards = Array.from({ length: 12 }, (_, i) => ({ id: String(i), name: `card ${i}`, hareruya2Url: `https://example.test/${i}` }));
const args = { cards, sourceId: "hareruya2", catalog: [], candidateRows: Object.fromEntries(cards.slice(0, 8).map((c) => [c.id, {}])), config: { importantHours: 6 }, now };
const first = plan(args);
assert.equal(first.queue.length, 12);
assert.deepEqual(first.queue.slice(0, 4).map((r) => r.important), [true, true, true, false]);
const row = { id: "0", url: cards[0].hareruya2Url, startedAt: new Date(now).toISOString(), status: "verified", important: true };
const saved = finish({}, row, new Date(now).toISOString(), { importantHours: 6 });
assert.equal(saved.nextDueAt, "2026-10-03T20:59:00.000Z");
const tomorrow = plan({ ...args, now: now + 120000, catalog: [{ cardId: "0", observedAt: new Date(now).toISOString(), price: 5000 }], jobs: { "0": saved } });
assert.equal(tomorrow.queue.some((r) => r.card.id === "0"), false, "JST day change must not reset progress");
const failed = finish(saved, { ...row, status: "failed", error: "HTTP 429" }, "2026-10-03T15:00:00Z");
assert.equal(failed.lastSuccessAt, saved.lastSuccessAt);
assert.equal(failed.nextDueAt, saved.nextDueAt);
assert.equal(plan({ ...args, jobs: { "0": failed } }).queue.some((r) => r.card.id === "0"), false);
assert.equal(plan({ ...args, jobs: { "0": { failures: 3, url: row.url } } }).queue.some((r) => r.card.id === "0"), false);
assert.equal(plan({ ...args, manualWait: { "0": { url: row.url } } }).queue.some((r) => r.card.id === "0"), false);
assert.equal(years.matches({ releaseYear: 2019 }, {}, true, false), false);
assert.equal(years.matches({ releaseYear: 2020 }, {}, true, false), true);
assert.equal(years.matches({ siteAddedAt: "2026-10-03", lastSaleAt: "2026-10-03" }, {}, true, false), false);
assert.equal(years.matches({}, {}, true, true), true);
assert.equal(years.matches({}, { ry: 2020 }, true, false), true);
assert.equal(years.matches({ releaseDate: "2019-12-31", releaseYear: 2026 }, {}, true, true), false);
assert.equal(due({ lastSuccessAt: new Date(now).toISOString(), lastAttemptAt: new Date(now).toISOString() }, now + 3600000), false);
assert.equal(due({ lastSuccessAt: new Date(now).toISOString() }, now + 21600000), true);
const input = { purchasePrice: 30000, currentPrice: 100000, fee: 13000, lockDays: 147,
  limit: { modelInput: { forecastPrice: 90000, saleFeeRate: 8 }, stressForecastPrice: 60000, assumptions: { hitRate: .7, lowerGradePrice: 40000 } } };
const mismatch = memo.trial(input, model);
assert.equal(mismatch.periodMatched, false);
assert.equal(mismatch.rows.central, null);
assert.equal(mismatch.rows.stress, null);
assert.ok(Number.isFinite(mismatch.rows.current.expectedProfit));
assert.equal(memo.trial({ ...input, lockDays: 91 }, model).periodMatched, true);
assert.equal(memo.trial({ ...input, lockDays: 35 }, model).rows.stress, null);
for (const lockDays of [42, 119, 147]) {
  const trial = memo.trial({ ...input, lockDays }, model);
  assert.equal(trial.rows.central, null);
  assert.equal(trial.rows.stress, null);
  assert.ok(Number.isFinite(trial.rows.current.expectedProfit));
  assert.match(trial.warning, new RegExp(`返却${lockDays}日`));
}
const app = fs.readFileSync(path.join(__dirname, "../app.js"), "utf8");
assert.match(app, /url.searchParams.set\("year2020", state.year2020Only/);
assert.match(app, /year2020Only: state.year2020Only/);
assert.ok(app.indexOf("releaseYearFilter.matches(card, completion") < app.indexOf("if (normalizedQuery && state.diagnosticSearch) return true"));
const refresh = fs.readFileSync(path.join(__dirname, "refresh_candidate_shops.js"), "utf8");
assert.doesNotMatch(refresh, /checkpoint.cycleDate === today/);
assert.match(refresh, /If-None-Match/);
assert.match(refresh, /sourceJobs.jobs\[card.id\] = priceQueue.finish/);
const workflow = fs.readFileSync(path.join(__dirname, "../.github/workflows/priority-price-refresh.yml"), "utf8");
assert.match(workflow, /20 \*\/2/);
assert.match(workflow, /all-site-data-refresh/);
assert.match(workflow, /publish_data_checkpoint.js/);
console.log("year boundaries, persistence, fair deadlines, failed-value retention, cache, plan horizon and publication tests passed");
