const assert = require("node:assert/strict");
const fs = require("node:fs");
const { eligibleForHareru } = require("./consume_completion_queue.js");
const { routes, failureState } = require("./completion_routes.js");
const { compare, pack, unpack } = require("./audit_completion_outcomes.js");
const { merge } = require("./recover_saved_psa.js");
const { psaIdentity, makeQueue } = require("./build_psa_linkage_queue.js");
const now = Date.parse("2026-10-06T04:00:00Z");
const rows = [{ card: { id: "psaOnly", hareruya2Url: "https://shop.example/1" }, detail: { m: ["psaOfficial"], i: { shopStateA: ["取得済み"], psaOfficial: ["取得待ち"] } } },
  { card: { id: "shopMissing", hareruya2Url: "https://shop.example/2" }, detail: { m: [], i: { shopStateA: ["取得待ち"] } } }];
assert.deepEqual(eligibleForHareru(rows, [], now).map((r) => r.card.id), ["shopMissing"]);
assert(routes(rows[0].detail).some((r) => r.key === "psaOfficial" && r.source === "psaOfficial"));
assert(!routes(rows[0].detail).some((r) => r.key === "shopStateA"));
assert.equal(routes({pk:"unexpanded-set", i:{pokedata:["取得待ち"]}}).find(r=>r.key==="pokedata").mode, "自動巡回中");
assert.equal(routes({pk:"unsupported-or-unconfirmed", i:{pokedata:["取得不能"]}}).find(r=>r.key==="pokedata").mode, "取得不能・存在未確認／照合待ち");
const first = failureState({}, { status: "failed", error: "HTTP 503", startedAt: new Date(now).toISOString() }, now);
assert(!first.held);
assert(!failureState(first, { status: "failed", error: "HTTP 503" }, now).held);
assert(failureState({}, { status: "failed", error: "HTTP 403" }, now).held);
const before = { at: "2026-10-05T00:00:00Z", schemaVersion: 2, rows: { one: { analysis: false, fields: ["domesticPrice"], sources: { psaOfficial: { linked: false, valid: false, fresh: false } } } } };
assert.deepEqual(unpack(pack(before)), { at: before.at, schemaVersion: 2, rows: { one: { ...before.rows.one, sources: Object.fromEntries(["cardrush", "hareruya2", "yuyutei", "torecacamp", "psaOfficial", "pokedata"].map((s) => [s, { linked: false, valid: false, fresh: false }])) } } });
const after = { at: new Date(now).toISOString(), rows: { one: { analysis: true, fields: ["domesticPrice", "psaOfficial"], sources: { psaOfficial: { linked: true, valid: true, fresh: true } } } } };
const diff = compare(before, after);
assert.equal(diff.newlyAnalyzable, 1); assert.equal(diff.filledCards, 1); assert.equal(diff.sources.psaOfficial.usableNet, 1);
assert.equal(diff.sources.cardrush.usableNet, 0); assert(!JSON.stringify(diff).includes("null"));
assert.equal(compare(after, after).filledCards, 0);
const pop = { setCode: "SV9", cardNo: "126", cardName: "Clefairy", sourceUrl: "https://www.psacard.com/pop/tcg-cards/2025/verified/292980", fetchedAt: "2026-10-05T00:00:00Z", psa10Count: 100, psaTotal: 120 };
assert.equal(merge([], [pop], now).audit.added, 1);
assert.equal(merge([pop], [{ ...pop, fetchedAt: "2026-10-04" }], now).rows[0].fetchedAt, pop.fetchedAt);
assert.equal(merge([], [{ ...pop, psa10Count: 121 }], now).audit.rejected, 1);
assert.deepEqual(psaIdentity({ name: "ピカチュウ [323 S-P]" }), { setCode: "S-P", cardNumber: "323" });
assert.deepEqual(psaIdentity({ name: "ルザミーネ [SM4+ 120/114]" }), { setCode: "SM4+", cardNumber: "120" });
const q = makeQueue({ cards: [{ id: "promo", name: "ピカチュウ [323 S-P]" }], population: {}, buybacks: {}, setDates: {}, setUrls: [{ setCode: "S-P", url: "a" }, { setCode: "S-P", url: "b" }], analysisIds: new Set(), now: new Date(now).toISOString() });
assert.equal(q.rows[0].status, "ambiguous"); assert.equal(q.rows[0].sourceSetUrl, null);
const published = JSON.parse(fs.readFileSync("data/completion-outcomes.json", "utf8"));
const status = JSON.parse(fs.readFileSync("data/update-status.json", "utf8"));
const completion = JSON.parse(fs.readFileSync("data/card-catalog-completion.json", "utf8"));
assert.deepEqual(status.unifiedMonitor.outcomes, published, "screen and downloadable audit must have identical counts");
assert.equal(published.counts.listed, completion.summary.total);
assert.equal(published.counts.analyzable, completion.summary.analyzable);
assert.equal(published.domesticPsa9IndividualCards, 0, "overseas PSA9 is not domestic completed acquisition");
assert.equal(published.sources.pokedata.valid, published.overseasAcquisition.usablePsa10MedianCards);
assert(!JSON.stringify(published).match(/NaN|Infinity/));
console.log("completion routes, same-cause hold, outcome deltas, saved PSA recovery, promo ambiguity: passed");
