const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {capture}=require('./capture_unpublished_data');
const {publish}=require('./publish_data_checkpoint');
const {strictMatch,select,recordFailure}=require('./discover_state_a_urls');
const {variantsCompatible}=require('./build_psa_history');
const snapshots=require('./integrate_saved_snapshots');
assert.deepEqual(snapshots.merge({a:1,b:1},{a:2,b:1},{a:1,b:3}),{a:2,b:3});
assert.throws(()=>snapshots.merge({a:1},{a:2},{a:3}),/Concurrent value conflict/);
assert.deepEqual(snapshots.mergeHistory({dates:['2026-10-06'],stocks:{a:[1]}},{dates:['2026-10-06','2026-10-07'],stocks:{a:[1,2]}},{dates:['2026-10-06'],stocks:{a:[1],b:[3]}}),{dates:['2026-10-06','2026-10-07'],stocks:{a:[1,2],b:[3,null]}});
assert(!variantsCompatible('ピカチュウ マスターボールミラー','Pikachu Master Ball Mirror',{set:'SV2A',name:'Pikachu |'}));
assert(variantsCompatible('ピカチュウ マスターボールミラー','Pikachu Master Ball Mirror',{set:'SV2A',name:'Pikachu Master Ball Reverse Holo'}));
assert(!variantsCompatible('ピカチュウ','Pikachu',{set:'SV2A',name:'Pikachu Master Ball Reverse Holo'}));
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pokeka-raw-recovery-'));
fs.mkdirSync(path.join(dir,'data'),{recursive:true});fs.mkdirSync(path.join(dir,'work'));
const summaryFile=path.join(dir,'data/shop.json');
fs.writeFileSync(summaryFile,JSON.stringify({cards:{fixture:{hareruya2Price:280000,stock:2,observedAt:'2026-10-07T02:49:37.987Z',identityVerifiedAt:'2026-10-07T02:49:37.987Z'}}}));
require('./update_hareruya2_stock').writeSummary([{id:'fixture'}],[],{dates:['2026-10-07'],stocks:{fixture:[2]}},{summary:summaryFile});
const savedShop=JSON.parse(fs.readFileSync(summaryFile,'utf8')).cards.fixture;
assert.equal(savedShop.hareruya2Price,280000,'list absence must not erase directly confirmed prices');
assert.equal(savedShop.observedAt,'2026-10-07T02:49:37.987Z');
assert.equal(savedShop.identityVerifiedAt,'2026-10-07T02:49:37.987Z');
fs.writeFileSync(path.join(dir,'data/broken.json'),'{broken');
fs.writeFileSync(path.join(dir,'work/checkpoint.json'),'{"next":42}');
fs.writeFileSync(path.join(dir,'ui-data-codec.js'),'throw new Error("summary failure")');
const raw=capture({cwd:dir,source:'priority-prices'});
assert.equal(raw.verified,true);assert.deepEqual(raw.invalidJson,['data/broken.json']);
assert.equal(fs.readFileSync(path.join(raw.directory,'work/checkpoint.json'),'utf8'),'{"next":42}');
assert.equal(publish({cwd:dir,captureOnly:true}).status,'raw-recovery-saved','no Git or summary dependency');
const card={id:'fixture',name:'ピカチュウ: プロモ [001/SV-P](プロモーションカード「SV-P」)'};
const product={title:'ピカチュウ(PROMO){雷}〈001/SV-P〉[SV-P]',handle:'fixture'};
assert(strictMatch(card,product));
assert(!strictMatch(card,{...product,title:product.title.replace('001/','002/')}));
for(const prefix of ['【状態A-】','【状態C】','PSA10 ','韓国版 ','マスターボールミラー ']) assert(!strictMatch(card,{...product,title:prefix+product.title}));
assert(strictMatch({name:'リーリエ SR[SM4+ 119/114](ハイクラスパック「GXバトルブースト」)'},{title:'リーリエ(SR){サポート}〈119/114〉[SM4p]'}));
assert(!strictMatch({name:'ミュウ UR[S8a 030/028](パック)'},{title:'ミュウ(SR){超}〈030/028〉[S8a]'}));
const now=Date.now(),queue={cards:{fixture:{m:['shopStateA'],p:5}}};
assert.equal(select([card],queue,{cards:{}},now).length,1);
assert.equal(select([card],queue,{cards:{fixture:{matcherVersion:2,matcherRevision:'strict-promo-prefix-v3',nextRetryAt:new Date(now+86400000).toISOString()}}},now).length,0);
assert.equal(select([card],queue,{cards:{fixture:{matcherVersion:2,matcherRevision:'strict-state-a-v2',nextRetryAt:new Date(now+86400000).toISOString()}}},now).length,1,'changed promo identification rechecks only affected cards');
assert.equal(select([card],queue,{cards:{fixture:{held:true}}},now).length,0);
const failures={};
recordFailure(failures,'broken',new Error('HTTP 503'),now);
assert.equal(failures.sourceRetry,undefined,'individual collection must not stop normal collections');
assert.equal(failures.collectionRetries.broken.status,'retry-wait');
recordFailure(failures,'broken',new Error('timeout'),now);
assert.equal(failures.collectionRetries.broken.held,false,'two transient errors do not force manual waiting');
recordFailure(failures,'access',new Error('HTTP 403'),now);
assert.equal(failures.sourceRetry.held,true,'access restriction stops this source without bypass');
const app=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8');
assert(app.includes("state.openCardDetails.has(String(card.id)) ? `"));
console.log('Independent raw backup, broken JSON preservation, exact URL matching and lazy detail regressions passed');
