const assert = require('node:assert/strict');
const ratio = require('../purchase-ratio-model.js');
const decision = require('../decision-model.js');
const base = {purchasePrice:1000,purchaseKind:'store',psa9:{value:1000,measurementType:'aggregate',currency:'JPY',country:'jp'},fee:1000,saleFeeRate:0,extraCost:0};
const zero = ratio.evaluate(base);
assert.equal(zero.nonLossCap,0);assert.equal(zero.nonLossStatus,'zero');assert(ratio.capLabel(zero).includes('0円仕入れで損益0円'));
const negative=ratio.evaluate({...base,fee:1001});
assert.equal(negative.nonLossCap,-1);assert.equal(negative.nonLossStatus,'impossible');assert.equal(ratio.capLabel(negative),'赤字回避できる仕入れ値なし');
const missing=ratio.evaluate({...base,psa9:{value:null}});
assert.equal(missing.nonLossCap,null);assert.equal(missing.nonLossStatus,'unavailable');assert.equal(ratio.capLabel(missing),'算出不可');
assert.equal(ratio.evaluate({...base,purchasePrice:1e308,psa9:{...base.psa9,value:1e-300}}).ratio,null);
assert.equal(ratio.evaluate({...base,fee:1e308,extraCost:1e308}).nonLossCap,null);
assert.equal(ratio.capLabel({nonLossCap:NaN,nonLossStatus:'available'}),'算出不可');
assert.equal(ratio.evaluate({...base,psa9:{value:1000}}).ratio,null);
const aggregate=ratio.evaluate({...base,fee:100});
assert(ratio.matches(aggregate,80,100,{aggregate:true}));assert(!ratio.matches(aggregate,80,100,{market:true}));
const market=ratio.evaluate({...base,purchaseKind:'market'});
assert(!ratio.matches(market,80,100,{aggregate:true}));assert(ratio.matches(market,80,100,{aggregate:true,market:true}));
const estimated=ratio.evaluate({...base,psa9:{...base.psa9,measurementType:'estimate',source:'PSA10 cohort estimate'}});
assert.equal(estimated.nonLossStatus,'zero');assert(!ratio.matches(estimated,80,100,{aggregate:true}));assert(ratio.matches(estimated,80,100,{estimate:true}));
const circular=ratio.evaluate({...base,psa9:{...base.psa9,measurementType:'estimate',source:'平均美品価格の75%推定'}});
assert.equal(ratio.eligibility(circular,{estimate:true}),'circular-estimate');assert(!ratio.matches(circular,80,100,true));
assert.equal(ratio.eligibility(missing,{aggregate:true}),'data-missing');
assert.equal(ratio.eligibility(aggregate,{}),'reference-disabled');
assert(ratio.matches(missing,null,null),'unset ratio filter must not remove deficient catalog cards');
const metrics = decision.resilienceMetrics({purchasePrice:1000,fee:1001,saleFeeRate:0,saleExtraCost:0,assumptions:{hitRate:.7,lowerGradePrice:1000}});
assert.equal(metrics.psa9NonLossMaxPrice,0,'production decision cap is retained');assert.equal(metrics.psa9NonLossRawPrice,-1);
assert.equal(decision.resilienceMetrics({fee:1000,assumptions:{lowerGradePrice:1000}}).psa9NonLossRawPrice,0);
assert.equal(decision.resilienceMetrics({fee:1000,assumptions:{lowerGradePrice:null}}).psa9NonLossRawPrice,null);
console.log('PSA9 signed cap, exact zero, missing, independent references and circular estimate exclusion passed');
