const assert = require("assert");
const fs = require("fs");
const path = require("path");
const runner = require("./run_safe_backfill.js");
const shops = require("./update_yuyutei_torecacamp.js");
const root = path.join(__dirname, "..");
const config = require("./safe-backfill-config.json");

const card = { id: "test-card", name: "テスト SR[S8 119/100]", price: 10000, snkPsa10Price: 20000, tv30: 0 };
const baseline = shops.yuyuteiPriority(card, {});
const oneItem = shops.yuyuteiPriority(card, {}, { oneItemAway: new Set([card.id]), priceReview: new Set() });
const priceReview = shops.yuyuteiPriority(card, {}, { oneItemAway: new Set(), priceReview: new Set([card.id]) });
assert(oneItem.rank < priceReview.rank && priceReview.rank < baseline.rank);
assert.equal(runner.command("yuyutei", config.sources.yuyutei).env.SHOP_MAX_FAILURES, "1");
assert.equal(runner.command("priceEvidence", config.sources.priceEvidence).env.PRICE_EVIDENCE_MAX_FAILURES, "2");
assert.equal(runner.lastJsonLine("noise\n{\"stopReason\":\"HTTP 403\"}\n").stopReason, "HTTP 403");
assert.equal(runner.batchFailureCount({ yuyutei: { failed: 1 } }, "yuyutei"), 1, "nested shop failures stop the runner");
assert.equal(runner.batchFailureCount({ failed: 2 }, "priceEvidence"), 2);
assert.equal(runner.complete("priceEvidence", { remaining: 1 }), false, "unverified pages are not completed");
assert.equal(runner.complete("priceEvidence", { remaining: 0 }), true);
const markup = fs.readFileSync(path.join(root, "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
assert(markup.indexOf('id="qInput"') < markup.indexOf('class="quick-presets"'));
assert.match(markup, /<label for="qInput">/);
assert.match(markup, /<label class="inline-check diagnostic-control" for="diagnosticSearchInput">/);
assert(!/<label class="control control-wide">[\s\S]*?<label class="inline-check"/.test(markup), "検索欄のラベルを入れ子にしない");
assert(markup.indexOf('class="quick-presets"') < markup.indexOf('id="candidateList"'));
assert(markup.includes('class="advanced-filters primary-settings"'));
assert(app.includes('aria-label="仕入れ判断の要点"'));
assert(app.includes('購入先確認済み・今すぐ仕入れ候補'));
assert(app.includes('プリセットのみ ${fmt.format(audit.presetOnly)} → 追加条件後 ${fmt.format(audit.final)}件'));
assert(app.includes('推奨仕入れ値ではありません'));
assert(app.includes('${purchaseSummaryPanel}') && app.includes('class="card-details"'));
assert(app.includes("prioritizeCandidateLayout();"), "advanced panels move below the candidate list");
assert(fs.readFileSync(path.join(root, "styles.css"), "utf8").includes(".shell>.stats,.shell>.stats-panel,.shell>.advanced-filters,.shell>.catalog-scope{order:6}"));
const styles = fs.readFileSync(path.join(root, "styles.css"), "utf8");
assert(styles.includes('.search-control #qInput') && styles.includes('min-height:46px'));
assert(styles.includes('.diagnostic-control #diagnosticSearchInput{flex:0 0 18px;width:18px'));
console.log("safe checkpoint and compact candidate layout: ok");
