const assert=require('node:assert/strict');
const {cellTextWithSpecification}=require('./update_psa_official_populations');
const {authoritativeRows,variantsCompatible,reconcileHistory}=require('./build_psa_history');
const {retryPolicy,canRecheck,sourceFingerprint,matcherRevision}=require('./discover_state_a_urls');
const now=Date.parse('2026-10-07T06:00:00Z'), day=86400000;
assert.equal(cellTextWithSpecification({childNodes:[{textContent:'Pikachu'},{textContent:' Master Ball Reverse Holo '},{textContent:'Shop with Affiliates'}]}),'Pikachu | Master Ball Reverse Holo | Shop with Affiliates');
assert(variantsCompatible('モンスターボール','Poke Ball',{set:'S8A-G',name:'Full Art/Poke Ball'}),'trainer name is not a mirror');
assert(variantsCompatible('メタモン','Ditto',{set:'SV2A',name:'Ditto'}),'Pokemon name alone is not Ditto-mark evidence');
assert(!variantsCompatible('ピカチュウ マスターボールミラー','Pikachu Master Ball Mirror',{set:'SV2A',name:'Pikachu Reverse Holo'}));
const old={set:'SV2A',url:'official',fetchedAt:'2026-10-01',name:'Pikachu'},fresh={...old,captureVersion:2,completeSnapshot:true,fetchedAt:'2026-10-07',name:'Pikachu Master Ball Reverse Holo'};
assert.deepEqual(authoritativeRows([old,fresh]),[fresh]);
assert.deepEqual(authoritativeRows([fresh,{...old,fetchedAt:'2026-10-08'}]),[fresh],'a newer legacy collector cannot reinstate specification-less rows');
assert.equal(authoritativeRows([old,{...fresh,completeSnapshot:false}]).length,2,'partial acquisition cannot displace complete old data');
const historyStore={},history=[['20261001',100,200]],identity={set:'SV2A',no:'25'};
assert.deepEqual(reconcileHistory(historyStore,'fixture',history,fresh,identity),[],'unknown old finish cannot create a false population jump');
assert.deepEqual(historyStore.quarantined.fixture[0].points,history,'raw history stays recoverable');
const corrected=[['20261007',300,400]];
assert.deepEqual(reconcileHistory(historyStore,'fixture',corrected,fresh,identity),corrected,'same identity does not reset history again');
const card={id:'fixture',name:'ピカチュウ C[SV2a 025/165](パック)'},item={m:['shopStateA'],rd:'2026-10-01'};
assert.equal(retryPolicy(card,item,now).days,1);
assert.equal(retryPolicy(card,{m:['a','b'],rd:'2016-01-01',r:['買取表30日10店舗日']},now).days,3);
assert.equal(retryPolicy(card,{m:['a'],rd:'2016-01-01'},now).days,7);
assert.equal(retryPolicy(card,{m:['a','b'],rd:'2016-01-01'},now).days,30);
const state={cards:{fixture:{matcherVersion:2,checkedAt:new Date(now-2*day).toISOString(),nextRetryAt:new Date(now+28*day).toISOString(),collection:'set',sourceFingerprint:'old'}},cache:{set:{fingerprint:'old'}}};
assert(canRecheck(card,item,state,now),'legacy 30-day delay shortened only for prioritized cards');
assert(!canRecheck(card,{m:['a','b'],rd:'2016-01-01'},state,now));
state.cache.set.fingerprint='changed';assert(canRecheck(card,{m:['a','b'],rd:'2016-01-01'},state,now));
state.cards.fixture.held=true;assert(!canRecheck(card,item,state,now),'changed listing cannot auto-release ambiguous identity');
assert.equal(sourceFingerprint([{id:1,title:'Pikachu',price:100}]),sourceFingerprint([{id:1,title:'Pikachu',price:200}]),'price-only change is not a reason to rematch');
assert.notEqual(sourceFingerprint([{id:1,title:'Pikachu'}]),sourceFingerprint([{id:1,title:'Pikachu mirror'}]));
assert.equal(matcherRevision(card,{defaultRevision:'v2',setRevisions:{SV2A:'v3'}}),'v3');
console.log('PASS: full PSA specifications, complete-snapshot precedence and adaptive targeted re-exploration');
