const assert = require('node:assert/strict');
const m = require('../decision-model.js');
const {plan} = require('./priority_price_queue.js');
const {issueCategory} = require('../update-health-model.js');
const now = Date.parse('2026-10-07T00:00:00Z');
const quote = (source,value,updatedAt,extra={}) => ({source,value,updatedAt,inventoryAt:updatedAt,kind:'販売価格',url:'https://example.test/'+source,available:true,identityVerified:true,inventoryKnown:true,...extra});
const rows = [quote('old1',10000,'2026-09-20'),quote('old2',10500,'2026-09-20'),quote('old3',11000,'2026-09-20'),quote('new',5000,'2026-10-06T23:00:00Z')];
const aggregation = m.aggregatePrices(rows,{asOfDate:'2026-10-07'});
const freshness = m.referenceFreshness(aggregation,now);
assert.deepEqual(freshness.freshVsOldSources,['new']);
assert.equal(freshness.recent,0); assert.equal(freshness.stale,3);
assert.equal(m.storeOffers(rows,aggregation,{now}).offer.source,'new');
assert.equal(m.purchasePriceState(m.storeOffers(rows.slice(0,3),aggregation,{now}).rows).code,'expired');
assert.equal(m.purchasePriceState([quote('stop',5000,null,{sourceBlocked:'HTTP 403'})]).code,'stopped');
assert.equal(m.purchasePriceState([quote('empty',5000,null,{fresh:true,available:false})]).code,'out-of-stock');
assert.equal(m.purchasePriceState([quote('unknown',null,null,{available:false,inventoryKnown:false})]).code,'unacquired');
assert.equal(m.referenceFreshness({included:[quote('unknown',1000,null)]},now).unknown,1);
const cards = Array.from({length:5},(_,i)=>({id:String(i),hareruya2Url:'https://example.test/'+i}));
const queue = plan({cards,catalog:[],sourceId:'hareruya2',candidateRows:{0:{currentMarket:true,priceRefreshReady:true},1:{},2:{},3:{}},now});
assert.equal(queue.queue[0].card.id,'0'); assert(queue.queue[0].reason.includes('現相場採算'));
assert.deepEqual(queue.queue.slice(0,4).map(r=>r.important),[true,true,true,false]);
assert.equal(issueCategory({reason:'遊々亭 HTTP 403'}),'アクセス・手動対応待ち');
assert.equal(issueCategory({reason:'独立監視未登録 / タスク登録権限不足。起動前失敗を捕捉するタスクは未登録'}),'アクセス・手動対応待ち');
assert.equal(issueCategory({key:'priority-prices:workflow-failure'}),'取得処理の故障');
assert.equal(issueCategory({reason:'3回連続で進捗なし'}),'鮮度未達・進捗停滞');
assert.equal(m.MODEL_VERSION,'purchase-decision-v5-shared-limits');
console.log('Purchase recovery, current-market queue, stale reference audit and warning categories PASS');
