const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { build, groupFor, fairBatch, observation } = require("./focus_monitor.js");
const { eligibleForHareru } = require("./consume_completion_queue.js");
const root = path.join(__dirname, "..");
const config = require("../data/focus-monitor-config.json");
const data = build(root);
assert.equal(data.count, 37);
assert.deepEqual(data.groups.map((g) => g.matched), [1, 36]);
assert.equal(groupFor({ name: "スターミーV CSR[S9a 084/067]", model: "084/067" }, config), null);
assert.equal(groupFor({ name: "イーブイ C[S6a 058/069]", model: "058/069" }, config), null);
const list = Array.from({ length: 100 }, (_, id) => ({ id, focus: id < 50 }));
assert.equal(fairBatch(list, 10, (r) => r.focus).filter((r) => r.focus).length, 4);
assert.equal(fairBatch(list, 6, (r) => r.focus).filter((r) => r.focus).length, 2);
assert.equal(fairBatch(list.filter((r) => r.focus), 6, (r) => r.focus).length, 6);
const now = Date.parse("2026-10-03T12:00Z");
const candidate = [{ card: { id: "a", hareruya2Url: "https://www.hareruya2.com/products/a" }, detail: { i: { shopStateA: ["取得待ち"] } } }, { card: { id: "b" }, detail: { i: { shopStateA: ["取得待ち"] } } }];
assert.equal(eligibleForHareru(candidate, [], now).length, 1);
assert.equal(eligibleForHareru(candidate, [{ cardId: "a", price: 100, observedAt: "2026-10-03T11:00Z" }], now).length, 0);
assert.equal(eligibleForHareru(candidate, [{ cardId: "a", price: 100, observedAt: "2026-10-04T11:00Z" }], now).length, 1);
assert.equal(observation(null, null, now, 48).value, null);
assert.equal(observation(100, null, now, 48).fresh, false);
assert.equal(observation(100, "2026-10-04", now, 48).fresh, false);
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "pokeka-focus-"));
try {
  fs.mkdirSync(path.join(temp, "data"));
  const save = (file, val) => fs.writeFileSync(path.join(temp, "data", file), JSON.stringify(val));
  save("focus-monitor-config.json", config);
  save("pokemon-cards.json", [{ id: "x", name: "スターミーV CSR[S9a 083/067]", model: "083/067" }]);
  save("psa-population-summary.json", { cards: { x: { ten: 0, total: 500, f: "2026-10-03T11:00Z" } } });
  const row = build(temp, now).cards.x;
  assert.equal(row.items.psaRate.value, 0);
  assert.equal(row.items.psaRate.status, "鮮度適合");
  assert.equal(row.items.domesticPsa10.value, null);
  save("psa-population-summary.json", { cards: { x: { ten: null, total: 500, f: "2026-10-03T11:00Z" } } });
  assert.equal(build(temp, now).cards.x.items.psaRate.value, null);
} finally { fs.rmSync(temp, { recursive: true }); }
console.log("focus monitoring and fair scheduling tests passed");
