const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'independent-monitor-'));
fs.mkdirSync(path.join(root,'data'));fs.mkdirSync(path.join(root,'work'));
const observer=require('./monitor_observation'),model=require('../update-health-model');
const success=observer.record(root,'observed',{newIssueCount:2});
const failed=observer.record(root,'failed',{error:'GitHub HTTP 503'});
assert.equal(failed.lastSuccessAt,success.lastSuccessAt,'failure cannot erase the previous observation');
assert(model.monitorIssues(failed).some(row=>row.key==='monitor:workflow-failure'));
assert(model.monitorIssues(success,Date.parse(success.lastSuccessAt)+6*3600000).some(row=>row.key==='monitor:stale'));
assert.equal(model.monitorIssues(success,Date.parse(success.lastSuccessAt)+3600000).length,0);
assert.notEqual(model.summarizeIssue({reason:'取得・検証・保存・公開のいずれかが未完了'}).cause,'保存後の公開失敗');
const data=observer.banner(root);
assert.equal(data.monitoring.lastSuccessAt,success.lastSuccessAt);
assert(!Object.hasOwn(data,'unifiedMonitor'),'banner never loads full card histories');
observer.record(root,'observed',{freshness:{hugeHistory:Array(10000).fill('history')},unpublishedData:Array(1000).fill({artifact:'details'})});
const compact=observer.banner(root);
assert(!Object.hasOwn(compact.monitoring,'freshness'));
assert(!Object.hasOwn(compact.monitoring,'unpublishedData'));
assert(JSON.stringify(compact).length<2000);
const observed=observer.record(root,'observed',{unpublishedData:[{runId:123,status:'pending'}]});
fs.writeFileSync(path.join(root,'data/source-recovery-audit.json'),JSON.stringify({runId:123,recoveredSourceFiles:21,publicationEvidence:{revision:'verified'}}));
observer.banner(root);
const annotated=JSON.parse(fs.readFileSync(path.join(root,'data/monitor-observation.json'),'utf8'));
assert.equal(annotated.lastSuccessAt,observed.lastSuccessAt);
assert.equal(annotated.lastAttemptAt,observed.lastAttemptAt);
assert(annotated.unpublishedData[0].status.includes('退避全体の完了とは別'));
const {execute}=require('./price_refresh_gate');
const partial=execute(root,()=>({sourceFailures:['buyback']}),{now:Date.now()});
assert.equal(partial.status,'acquired-saved');assert.equal(partial.acquisitionStatus,'partial-with-failure');
assert.throws(()=>execute(root,()=>{throw Error('required calculation failed');},{now:Date.now()+3*3600000}),/required calculation/);
const workflow=fs.readFileSync(path.join(__dirname,'../.github/workflows/watch-data-health.yml'),'utf8');
assert(workflow.includes('needs: catchup\n    if: always()'),'monitor must run after catchup failure');
assert(workflow.includes("steps.observation.outcome == 'success'"));
assert(!workflow.includes('continue-on-error'));
assert(workflow.indexOf('Publish independent validated monitor state')<workflow.indexOf('Report newly detected alerts'));
const priority=fs.readFileSync(path.join(__dirname,'../.github/workflows/priority-price-refresh.yml'),'utf8');
assert(priority.indexOf('Verify safety')<priority.indexOf('Publish validated data'));
assert(priority.indexOf('Publish validated data')<priority.indexOf('Report independent acquisition failures'));
const discovery=require('./discover_state_a_urls');
const card={name:'ピカチュウ RR :1ED [CP3 010/032](パック)'};
const product={title:'ピカチュウ(RR){雷}〈010/032〉[CP3]',handle:'fixture'};
assert(!discovery.strictMatch(card,product));
assert(discovery.diagnose(card,[product]).reasons['初版表記未確認']);
assert(discovery.diagnose(card,[]).reasons['同一番号の掲載未確認']);
const promo={name:'ピカチュウ: プロモ[XY-P 208/XY-P](商品)'};
const promoProduct={title:'ピカチュウ(PROMO){雷}〈208/XY-P〉[XY-P]',handle:'fixture'};
assert(discovery.strictMatch(promo,promoProduct));
assert(!discovery.strictMatch({...promo,name:promo.name.replace('208/XY-P','208/S-P')},promoProduct));
assert(!discovery.strictMatch({...promo,name:promo.name+'【中国語版】'},promoProduct));
console.log('PASS: source failures vs required failures, independent monitor, stale monitor, compact banner and edition safeguards');
