const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const { classify } = require('./automatic_operation');
const { decision, execute } = require('./price_refresh_gate');
const now = Date.parse('2026-10-07T13:00:00Z'), iso = ms => new Date(ms).toISOString();
assert.deepEqual(classify({enabled:true,intervalMs:7200000,now}).states,['設定有効','実行間隔未達']);
assert(classify({enabled:true,periodicSuccessAt:iso(now-3600000),intervalMs:7200000,now}).states.includes('定期成功'));
assert(!classify({enabled:true,acquiredAt:iso(now),savedAt:iso(now),publishedAt:iso(now),intervalMs:7200000,now}).states.includes('定期成功'),'manual acquisition/publication is not scheduled success');
assert.deepEqual(classify({enabled:true,hold:'認証切れ',intervalMs:7200000,now}).states,['設定有効','認証待ち']);
assert(classify({enabled:true,hold:'HTTP 403',intervalMs:7200000,now}).states.includes('アクセス停止'));
assert.deepEqual(classify({enabled:false,implemented:false,now}).states,['未実装']);
assert(classify({enabled:true,running:true,intervalMs:7200000,now}).states.includes('実行中'));
assert.equal(decision({startedAt:iso(now-2*3600000)},now,true).allowed,false,'30 minute cron grace');
assert.equal(decision({startedAt:iso(now-3*3600000)},now,true).allowed,true,'missed run is filled');
assert.equal(decision({startedAt:iso(now-3*60000)},now,false).allowed,false,'priority run immediately after catchup makes no requests');
assert.equal(decision({startedAt:iso(now+60000)},now,false).allowed,false);
assert.equal(decision({},now,true).allowed,true);
const planned=require('./priority_price_queue').plan({cards:[{id:'a',hareruya2Url:'https://example.test/product'}],sourceId:'hareruya2',
  catalog:[{cardId:'a',observedAt:iso(now-3*60000)}],candidateRows:{a:{}},config:{observedSuccessfulIntervalMs:12*3600000},now});
assert.equal(planned.queue.length,0,'daily acquisition immediately before catchup is not fetched again');
const root = fs.mkdtempSync(path.join(os.tmpdir(),'price-refresh-gate-'));
fs.mkdirSync(path.join(root,'work')); fs.mkdirSync(path.join(root,'data'));
fs.writeFileSync(path.join(root,'data/priority-price-execution.json'),JSON.stringify({startedAt:iso(now-60000)}));
let calls = 0;
assert.equal(execute(root,()=>calls++,{now,catchup:true}).status,'skipped');
assert.equal(calls,0);
fs.writeFileSync(path.join(root,'data/priority-price-execution.json'),JSON.stringify({startedAt:iso(now-3*3600000)}));
const completed = execute(root,()=>calls++,{now,catchup:true});
assert.equal(completed.status,'acquired-saved');
assert.equal(completed.publicationStatus,'保存済み・公開照合待ち','acquisition is not publication');
assert.equal(calls,1);
assert.throws(()=>execute(root,()=>{throw new Error('test failure');},{now,catchup:true}),/test failure/);
assert.equal(JSON.parse(fs.readFileSync(path.join(root,'data/price-catchup-status.json'))).status,'failed');
assert(!fs.existsSync(path.join(root,'work/priority-price-refresh.lock')),'failed batch releases process ownership');
const release=require('./acquisition_retry').lock(path.join(root,'work/priority-price-refresh.lock'));
assert.throws(()=>execute(root,()=>calls++,{now,catchup:true}),/already running/);
release();
const workflow=fs.readFileSync(path.join(__dirname,'../.github/workflows/watch-data-health.yml'),'utf8');
assert(workflow.includes('node work/run_priority_price_refresh.js --catchup'));
assert(workflow.includes("steps.catchup_validation.outcome == 'success'"),'invalid acquired data must not be published');
assert(workflow.includes('group: all-site-data-refresh'));
assert(!workflow.includes('actions: write'),'no new dispatch permission or AI task');
console.log(JSON.stringify({automaticStatus:'passed',missedRunCatchup:'passed',duplicateFetch:'passed',validationBeforePublication:'passed',llmCalls:0}));
